### ISSUE TITLE
麻烦完善一下文档及添加一下配置示例

### ISSUE THREAD

**Issue by waset** [s3xysteak/unplugin-iconify-generator#1]
通过 `README` 并不能支持我实现该插件的功能，`node_modules/unplugin-iconify-generator` 文件夹下并没有自动生成`json` 文件。
建议增加一下 `vscode` 和 `nuxt` 的配置示例，以及如何将生成的文件配置到 `.vscode/settings.json` 以支持 `antfu.iconify` 扩展

**Comment by s3xysteak** [comment]
[Here](https://github.com/s3xysteak/unplugin-iconify-generator/tree/main/test/playground)
这看起来是个bug。传入插件选项后 应该不需要其他配置就能正常工作了 😰 

看起来文档的用语有些不恰当，其实给插件指出了图标位置后，接下来都是自动进行的部分

**Comment by waset** [comment]
在上面我是用的是`nuxt`进行的配置，并不能起作用，我又测试了`vite`项目，看起来是能正常工作，但是并没有解析到对应的 `svg`文件
<img width="582" alt="image" src="https://github.com/user-attachments/assets/da65ef9a-b2c2-4109-9656-8a58ba31454a">
<img width="463" alt="image" src="https://github.com/user-attachments/assets/901d5844-82b8-466a-b931-9689493c6e24">
<img width="366" alt="image" src="https://github.com/user-attachments/assets/f792e0e8-ca3b-4f8c-b254-3c0efa4aec58">

**Comment by waset** [comment]
> 通过`README`并不能支持我实现该插件的功能，`node_modules/unplugin-iconify-generator`文件夹下并没有自动生成`json`文件。 建议增加一些`vscode`和`nuxt`的配置示例，以及如何将生成的文件配置到`.vscode/settings.json`支持`antfu.iconify`扩展
> 
> 以下为`nuxt`配置结果 <img alt="图像" width="542" src="https://private-user-images.githubusercontent.com/55943270/376856574-43d6f30a-073b-4a1c-84b4-8b4a94d544ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDUwMzQsIm5iZiI6MTcyOTA0NDczNCwicGF0aCI6Ii81NTk0MzI3MC8zNzY4NTY1NzQtNDNkNmYzMGEtMDczYi00YTFjLTg0YjQtOGI0YTk0ZDU0NGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAyMTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YjM1OTU3Njc4NTIyZmMzMWYxMDJiMTE3MmExYjk2YmU3YzhmZWU5YjhmZDBkOTk0NDhmMmJhYzg3MDBiMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lryexn-sJfDv3t9tnOUn997UHkwM42dC4hC_rugq8qA"> <img alt="图像" width="322" src="https://private-user-images.githubusercontent.com/55943270/376857347-5d2b69e7-06cb-4c29-b163-76226f57c382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDUwMzQsIm5iZiI6MTcyOTA0NDczNCwicGF0aCI6Ii81NTk0MzI3MC8zNzY4NTczNDctNWQyYjY5ZTctMDZjYi00YzI5LWIxNjMtNzYyMjZmNTdjMzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAyMTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzOGNjMjczMmIyZTc5ODA3YTFiYmM5ZGJlMzg5ODMzNzk1NjkyYmRmYWZjODE5MGJmOGIwMThlYTRmMDc5OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._WtgX2958TTsAqWWMkKzuLyBGpDOHmKOXbs0BM8huUg">
> 
> 并没有`node_modules/unplugin-iconify-generator`在下生成`json`文件 而中提到的并没有该文件 <img alt="图像" width="315" src="https://private-user-images.githubusercontent.com/55943270/376856987-77a35e98-a987-403f-8641-12c3c3d5672e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDUwMzQsIm5iZiI6MTcyOTA0NDczNCwicGF0aCI6Ii81NTk0MzI3MC8zNzY4NTY5ODctNzdhMzVlOTgtYTk4Ny00MDNmLTg2NDEtMTJjM2MzZDU2NzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAyMTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YjEyMTFhYjcwMGNjNTk0NjMyMDdlNTVlZjBjNjdjYTk1MDNlYTJhYTc4MTBkNzY1OTZlZDMyZWVjMmE4Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2_kGvt2ZO2NTOOFlhHA3g3U6Bnavarn0r1Mxxfiv3zs">`README``./node_modules/.unplugin-iconify-generator` <img alt="图像" width="580" src="https://private-user-images.githubusercontent.com/55943270/376857226-79c4dcfa-8c68-41f2-b2b3-f106dc24c9b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDUwMzQsIm5iZiI6MTcyOTA0NDczNCwicGF0aCI6Ii81NTk0MzI3MC8zNzY4NTcyMjYtNzljNGRjZmEtOGM2OC00MWYyLWIyYjMtZjEwNmRjMjRjOWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAyMTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2Mjg1NzE4MDMzYTlmMTZiYWQzMjA0MzlmZjY3MDI1OTVmNGQ3NWJhN2JkOGMyZjMzY2FhMDYxNDI0NTlmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pB0_3ixz4CV69TOaOK6T5URjiB3oWbNHYnDRxaXAKVA">


不好意思，我检查了一下 `nuxt` 的配置，我把路径配置错了，现在可以在 `nuxt` 中正常使用了，
<img width="514" alt="image" src="https://github.com/user-attachments/assets/30f8b400-a85a-4aef-b696-31562cf0e5fd">

**Comment by s3xysteak** [comment]
我考虑增加一些debug方式，这种不生效的情况确实有点摸不着头脑

你也可以指定绝对路径，这通常能保证路径正确：
```js
import { fileURLToPath, URL } from 'node:url'

// ...
Iconify({
  collections: {
    hi: fileURLToPath(new URL('./src/icons', import.meta.url)),
  },
}),
```

**Comment by waset** [comment]
> 在上面我是用的是`nuxt`进行的配置，并不能起作用，我又测试了`vite`项目，看起来是能正常工作，但是并没有解析到对应的 `svg`文件
> <img width="463" alt="image" src="https://github.com/user-attachments/assets/901d5844-82b8-466a-b931-9689493c6e24">

我测试了一下，找到了我的 `vite` 没有解析的原因:
由于部分文件太大，对所有`svg`进行了压缩，导致没有解析。
已压缩：
![crate.svg](https://github.com/user-attachments/assets/c7f16eee-d9bb-47ba-8cee-3e6ccbda20df)
未压缩：
![crosspath.svg](https://github.com/user-attachments/assets/41137c3d-3f30-4a01-a7f2-0d747f897183)

**Comment by waset** [comment]
可否让我成为该库开发者，我想将我的一些想法及原来的经验实现加入

- 修改 svg 编译逻辑为基于 [@iconify/tools](https://github.com/iconify/tools) 进行编译
- 增加配置项和逻辑，区分纯色图标和多色图标，多色图标直接使用，纯色图标可以使用 css 修改颜色
- 抛出方法，以支持快速导入图标集
<img width="436" alt="image" src="https://github.com/user-attachments/assets/41f56ce3-6c83-408c-9c9e-0961eddfbc7e">

**Comment by s3xysteak** [comment]
1. 这是个todo项，但最近小公司在加班没时间搞 :sob: 欢迎PR！
2. 这个最初是一个feature，后来做一半给这功能去了，因为我测试时感觉这个需求好像没啥用
3. 这个`'icon-user': './assets/icons/user'`就行
4. 这个我也考虑过，目前因为需要fs.watch，必须要获取路径，所以只能基于文件系统实现。除非把刷新和载入图标分为两个选项。当时觉得这样的话没什么直觉性的API，就暂时搁置了。如果有什么好点子欢迎讨论

**Comment by waset** [comment]
> 1. 这是个todo项，但最近小公司在加班没时间搞 😭 欢迎PR！

是想加入仓库，可以规范一下协作，互相检查代码以及审批

> 2. 这个最初是一个feature，后来做一半给这功能去了，因为我测试时感觉这个需求好像没啥用

单色图标的应用场景为鼠标经过后变换颜色、暗黑模式或者多主题切换等等，如果不区分的话会造成 svg 文件冗余和编译冗余，多个图标仅仅是颜色不同而代码等都一模一样

> 3. 这个`'icon-user': './assets/icons/user'`就行

增加配置项，默认不开启，我原项目也是没有进行区分，但是一个图标集都有上百图标，如果不进行目录区分会不好维护，后来团队规范目录引用，同一个图标集内按目录区分为 公共`common`、模块`user、product、order`、路由等，团队协作更好维护。

> 4. 这个我也考虑过，目前因为需要fs.watch，必须要获取路径，所以只能基于文件系统实现。除非把刷新和载入图标分为两个选项。当时觉得这样的话没什么直觉性的API，就暂时搁置了。如果有什么好点子欢迎讨论

不需要 watch 可以仅生成为对象合并就行

**Comment by s3xysteak** [comment]
随意邀请随机路人加入感觉很奇怪，应该不会有人这么做吧 :innocent:

> 鼠标经过后变换颜色、暗黑模式或者多主题切换

这个听起来是unocss的presetIcons在products里做的事情，vscode-iconify好像没有这个feature

> 不需要 watch 可以仅生成为对象合并就行

没看明白，能详细点解释嘛？如果不基于文件系统的话，怎么知道在什么时候更新呢？
